### ISSUE TITLE
The future of Livestreamer Twitch GUI

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-twitch-gui#331]
Let me just quickly talk about future plans and what's going on.

Due to the lack of updates of Livestreamer, a lot of things have been broken recently and needed to be fixed here in the GUI in order to make everything work again. Since Livestreamer's maintainer hasn't commited any changes and hasn't responded to any issues in almost a year now and as it seems that the whole project has been abandoned, a fork called [Streamlink](https://github.com/streamlink/streamlink) was created a couple of weeks ago.

A large amount of bugs have already been fixed in Streamlink by multiple, hard working people and although the project is just in its early stages, it's already looking great. There are still a couple of issues, like a potential naming conflict, but it seems that everything's okay. Packages and installers are being worked on and will be available soon.

As you can probably guess, further relying on Livestreamer is going to cause issues sooner or later. Breaking changes of Twitch's streaming infrastructure can happen at any time and that's why a switch over to Streamlink is inevitable. It's actually quite a relief, because critical bugs can get fixed, which will ensure the future of the GUI.

Right now, both Livestreamer and Streamlink are compatible with each other and work the same. Support for Streamlink has been added here in the GUI in the latest release ([`v0.16.0`](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.16.0)), and it can be chosen as an alternative in the settings menu. There are plans for the the CLI of Streamlink to be changed though, which could make both applications become incompatible with each other. I don't know if I want to support both Livestreamer and Streamlink if that's the case. Another reason to drop support for a non-future-proof Livestreamer.

So what does this all mean for **Livestreamer Twitch GUI**? Does it need to be renamed if the focus will be on Streamlink in the future? I would say so, yes. In addition to just renaming it, I'm also intending on moving the repo over to the Streamlink github organization. I'm not sure when this will happen, though.

Renaming and moving repos on Github is be pretty easy and automatic redirections will be created, so visitors of the old URLs won't see 404 errors. I'm not sure if the github API does this as well, though. If it doesn't, this would mean that the internal version check of the GUI will break.

And that's the next thing I want to talk about. How would a smooth transition of the project look like update-wise? A lot of people are just downloading the archives after being notified by the internal version check service. This kind of transition should be fairly simple, but there are also the AUR, chocolatey and homebrew-cask packages. Also, my work on the Windows installer and deb/rpm packages with custom package repos (#319) is almost done, but thinking about it, it would be wiser to wait for these to be published until the naming transition has been completed.

Maybe an intermediate release will be needed that informs the user about all the changes.

## Checklist

- [x] Wait for the Streamlink naming issue to be resolved
- [x] Add support for Streamlink  
  - [x] Add basic support (`v0.16.0`)
  - [x] Fix issues with Streamlink on Windows (f29484b869501fcab21c795e5ce424e7e5544515)
  - [x] Rewrite stream launch logic to support choosing between Streamlink and Livestreamer
  - [x] Remove all static references to Livestreamer (templates, JS modules, etc.)
- [x] Rename repo and move it over to the streamlink github orga  
  - [x] Merge #345  
    - [x] Rename the application
    - [x] Change all links
    - [x] Update Linux launcher/icon setup scripts
    - [x] Update documentation and wiki (will be merged once repo has moved)
    - [x] Prepare changes for packages  
      - [x] AUR
      - [x] Chocolatey
      - [x] Homebrew cask
- [x] Check third party services 
  - [x] Travis-CI
  - [x] Gitter
- [x] Add Windows installer
  - [ ] Implement internal upgrade system (postponed)
- [ ] Add deb/rpm packages (postponed) (#319)
- [x] Publish new release  
  - [x] Major version bump `1.0.0`
  - [x] Rename Twitch OAuth App

🎉 🎉 🎉

**Comment by LautaroCuello** [comment]
> Extend Linux launcher/icon setup scripts

Thanks, for your work.

**Comment by jsynth** [comment]
what with youtube-dl ?

**Comment by TheDromundKaas** [comment]
On only a semi-related note, I'd really like to support the project financially. Any chance for that?

**Comment by Magciool** [comment]
Hey you say in v0.16.0 you can now use streamlink and switch livestreamer for streamlink in teh settings, I can not find that option though in any of the settings tabs?

**Comment by bastimeyer** [comment]
@LautaroCuello 
Is there something wrong with the current launcher/icon setup scripts (`start.sh`, `{add,remove}-menuitems.sh`), or why are you quoting this line? Maybe you're confusing this with the addition of packages for Debian, *buntu, Mint, Elementary, Fedora, openSUSE, etc... #319 

@jsynth 
yt-dl works differently and is not a good option for streaming content.
streamlink/streamlink#7

@TheDromundKaas 
If you want to support and donate, you can find informations [on each of the releases pages](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/latest). Thanks!

@Magciool 
LS and SL are working identically right now, so you can simply change the executable path in the "livestreamer settings menu" to streamlink. All LS related bugfixes in the GUI are compatible with SL.
What I mentioned in the changelog was an addition to the validation routine for the SL executable, thus the word "initial support". Once new features are added to streamlink or once something becomes incompatible there will be different settings in the GUI for choosing between both. In case livestreamer breaks, it will be removed.

**Comment by Magciool** [comment]
@bastimeyer thanks 
I tried that but I had Python installed in a path with spaces in the directory and it just wouldn't work. But apparently that's a bug with python that some scripts don't work if there is a space in the directory path. 
So reinstalled python to another directory now works like a charm.

**Comment by SanyaIV** [comment]
Do they actually work completely the same with Livestreamer GUI? I'm wondering because after I switched to Streamlink, when I start a stream it will open a new CMD window instead of having the output in the Livestreamer GUI window. Not THAT big of a deal but it's yet another window cluttering my taskbar, just an aesthetics thing..

**Comment by bastimeyer** [comment]
I'm guessing you're on Windows...

The Windows cmd window is not supposed to be there and also causes issues when trying to close the process from within the GUI. I don't know why the cmd window is being opened, but it has something to do with the binary and python being started in a subprocess.

The streamlink installer causes the same issue that Livestreamer has when being installed via pip on Windows. That's the reason why it is mentioned in the readme and wiki.

The Windows installer for streamlink is still experimental, since it was rewritten and a different tool is now being used, but this may even be worth a bug report. I haven't had time to investigate this yet, but I will make sure that this gets fixed before the transition.

**Comment by SanyaIV** [comment]
@bastimeyer I'm indeed on Windows. I just used the Windows installer for version 0.0.2 that was available for download on the release page of Streamlink.

**Comment by Koonboi** [comment]
In one of the installers there is a bat file to run Streamlink. If you change python.exe to pythonw.exe the cmd window no longer shows up.

**Comment by chikei** [comment]
@Koonboi I believe you actually means **streamlink-script.py** :), edit first line of this file `#!"C:\Prog...\python.exe` from `python.exe` to `pythonw.exe` will do the trick

**Comment by Koonboi** [comment]
@chikei That too. The windows build I found was a comment in the issues, and it was started with a batch file. So I edited that.

**Comment by bastimeyer** [comment]
The streamlink launch logic has been rewritten, see https://github.com/bastimeyer/livestreamer-twitch-gui/issues/336#issuecomment-258585571.
Not yet merged into master, testing encouraged, though...

**Comment by bastimeyer** [comment]
`v1.0.0` has been released:
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

**Comment by bastimeyer** [comment]
It's been a month... Closing the thread now...
